### ISSUE TITLE
[EPIC] CLI Codegen

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#607]
* [x] Get the local codegen demo running
* [x] Draft/sketch the CLI codegen API #606
* [x] Add a CLI command to call the codegen demo server
  * [x] signature generation step
  * [x] code generation step
  * [ ] test generation step
* [x] Implement new 'apollo' server in gen https://github.com/OpenFn/gen/pull/44
* [x] Implement a generic apollo command #680
* [ ] Re-implement a `generate adaptor` command using the new AI server. Should write results straight into the monorepo if `-m` is passed
* [x] Deploy the AI server https://github.com/OpenFn/gen/issues/50

**Comment by christad92** [comment]
@josephjclark can I move this to in-progress?

**Comment by josephjclark** [comment]
@christad92 I suppose so but the main issue for this is tracked in `gen`, see https://github.com/OpenFn/gen/issues/42

**Comment by christad92** [comment]
That's okay. This is at an epic level so we will be fine.
